# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SilenceSpeechSys2.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1176, 871)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.mainGridLayout = QtWidgets.QGridLayout()
        self.mainGridLayout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.mainGridLayout.setSpacing(0)
        self.mainGridLayout.setObjectName("mainGridLayout")
        self.TitleWidget = QtWidgets.QWidget(self.centralwidget)
        self.TitleWidget.setObjectName("TitleWidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.TitleWidget)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.titlelabel = QtWidgets.QLabel(self.TitleWidget)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(15)
        self.titlelabel.setFont(font)
        self.titlelabel.setAutoFillBackground(False)
        self.titlelabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.titlelabel.setObjectName("titlelabel")
        self.horizontalLayout_3.addWidget(self.titlelabel)
        self.mainGridLayout.addWidget(self.TitleWidget, 0, 0, 1, 1)
        self.shutWidget = QtWidgets.QWidget(self.centralwidget)
        self.shutWidget.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.shutWidget.sizePolicy().hasHeightForWidth())
        self.shutWidget.setSizePolicy(sizePolicy)
        self.shutWidget.setMinimumSize(QtCore.QSize(100, 20))
        self.shutWidget.setBaseSize(QtCore.QSize(100, 50))
        self.shutWidget.setObjectName("shutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.shutWidget)
        self.horizontalLayout.setContentsMargins(500, -1, -1, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.miniButton = QtWidgets.QPushButton(self.shutWidget)
        self.miniButton.setText("")
        self.miniButton.setObjectName("miniButton")
        self.horizontalLayout.addWidget(self.miniButton)
        self.visitButton = QtWidgets.QPushButton(self.shutWidget)
        self.visitButton.setText("")
        self.visitButton.setObjectName("visitButton")
        self.horizontalLayout.addWidget(self.visitButton)
        self.closeButton = QtWidgets.QPushButton(self.shutWidget)
        self.closeButton.setText("")
        self.closeButton.setObjectName("closeButton")
        self.horizontalLayout.addWidget(self.closeButton)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 1)
        self.horizontalLayout.setStretch(2, 1)
        self.mainGridLayout.addWidget(self.shutWidget, 0, 1, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget.setUsesScrollButtons(False)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setObjectName("tabWidget")
        self.trainWidget = QtWidgets.QWidget()
        self.trainWidget.setObjectName("trainWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.trainWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.trainLeftWidget = QtWidgets.QWidget(self.trainWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.trainLeftWidget.sizePolicy().hasHeightForWidth())
        self.trainLeftWidget.setSizePolicy(sizePolicy)
        self.trainLeftWidget.setMinimumSize(QtCore.QSize(100, 719))
        self.trainLeftWidget.setBaseSize(QtCore.QSize(100, 0))
        self.trainLeftWidget.setObjectName("trainLeftWidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.trainLeftWidget)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_1 = QtWidgets.QLabel(self.trainLeftWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.label_1.setFont(font)
        self.label_1.setObjectName("label_1")
        self.verticalLayout.addWidget(self.label_1)
        self.showLabel_1 = QtWidgets.QLabel(self.trainLeftWidget)
        font = QtGui.QFont()
        font.setPointSize(35)
        font.setBold(True)
        font.setWeight(75)
        self.showLabel_1.setFont(font)
        self.showLabel_1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.showLabel_1.setFrameShadow(QtWidgets.QFrame.Plain)
        self.showLabel_1.setText("")
        self.showLabel_1.setAlignment(QtCore.Qt.AlignCenter)
        self.showLabel_1.setWordWrap(False)
        self.showLabel_1.setObjectName("showLabel_1")
        self.verticalLayout.addWidget(self.showLabel_1)
        self.label_2 = QtWidgets.QLabel(self.trainLeftWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.showLabel_2 = QtWidgets.QLabel(self.trainLeftWidget)
        font = QtGui.QFont()
        font.setPointSize(35)
        font.setBold(True)
        font.setWeight(75)
        self.showLabel_2.setFont(font)
        self.showLabel_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.showLabel_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.showLabel_2.setText("")
        self.showLabel_2.setAlignment(QtCore.Qt.AlignCenter)
        self.showLabel_2.setWordWrap(False)
        self.showLabel_2.setObjectName("showLabel_2")
        self.verticalLayout.addWidget(self.showLabel_2)
        self.startTrain = QtWidgets.QPushButton(self.trainLeftWidget)
        self.startTrain.setObjectName("startTrain")
        self.verticalLayout.addWidget(self.startTrain)
        self.stopTrain = QtWidgets.QPushButton(self.trainLeftWidget)
        self.stopTrain.setObjectName("stopTrain")
        self.verticalLayout.addWidget(self.stopTrain)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 2)
        self.verticalLayout.setStretch(2, 1)
        self.verticalLayout.setStretch(3, 2)
        self.verticalLayout.setStretch(5, 1)
        self.verticalLayout_4.addLayout(self.verticalLayout)
        self.gridLayout_2.addWidget(self.trainLeftWidget, 0, 0, 1, 1)
        self.trainRightwidget = QtWidgets.QWidget(self.trainWidget)
        self.trainRightwidget.setObjectName("trainRightwidget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.trainRightwidget)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setSpacing(0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.videoTrainLabel = QtWidgets.QLabel(self.trainRightwidget)
        self.videoTrainLabel.setText("")
        self.videoTrainLabel.setObjectName("videoTrainLabel")
        self.gridLayout_4.addWidget(self.videoTrainLabel, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.trainRightwidget, 0, 1, 1, 1)
        self.gridLayout_2.setColumnStretch(0, 1)
        self.gridLayout_2.setColumnStretch(1, 7)
        self.gridLayout.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        self.tabWidget.addTab(self.trainWidget, "")
        self.preWidget = QtWidgets.QWidget()
        self.preWidget.setObjectName("preWidget")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.preWidget)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setSpacing(0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.preLeftWidget = QtWidgets.QWidget(self.preWidget)
        self.preLeftWidget.setObjectName("preLeftWidget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.preLeftWidget)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.selectLabel = QtWidgets.QLabel(self.preLeftWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.selectLabel.setFont(font)
        self.selectLabel.setObjectName("selectLabel")
        self.verticalLayout_2.addWidget(self.selectLabel)
        self.listPreWidget = QtWidgets.QListWidget(self.preLeftWidget)
        self.listPreWidget.setObjectName("listPreWidget")
        item = QtWidgets.QListWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(48)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.listPreWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(48)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.listPreWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(48)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.listPreWidget.addItem(item)
        self.verticalLayout_2.addWidget(self.listPreWidget)
        self.startPreButton = QtWidgets.QPushButton(self.preLeftWidget)
        self.startPreButton.setObjectName("startPreButton")
        self.verticalLayout_2.addWidget(self.startPreButton)
        self.stopPreButton = QtWidgets.QPushButton(self.preLeftWidget)
        self.stopPreButton.setObjectName("stopPreButton")
        self.verticalLayout_2.addWidget(self.stopPreButton)
        self.verticalLayout_2.setStretch(0, 1)
        self.verticalLayout_2.setStretch(1, 7)
        self.verticalLayout_2.setStretch(2, 2)
        self.verticalLayout_2.setStretch(3, 2)
        self.verticalLayout_5.addLayout(self.verticalLayout_2)
        self.gridLayout_3.addWidget(self.preLeftWidget, 0, 0, 1, 1)
        self.preMidWidget = QtWidgets.QWidget(self.preWidget)
        self.preMidWidget.setObjectName("preMidWidget")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.preMidWidget)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setSpacing(0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.videoPrelabel = QtWidgets.QLabel(self.preMidWidget)
        self.videoPrelabel.setText("")
        self.videoPrelabel.setObjectName("videoPrelabel")
        self.gridLayout_6.addWidget(self.videoPrelabel, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.preMidWidget, 0, 1, 1, 1)
        self.preRightWidget = QtWidgets.QWidget(self.preWidget)
        self.preRightWidget.setObjectName("preRightWidget")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.preRightWidget)
        self.verticalLayout_6.setContentsMargins(9, -1, -1, -1)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.preLabel = QtWidgets.QLabel(self.preRightWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.preLabel.setFont(font)
        self.preLabel.setObjectName("preLabel")
        self.verticalLayout_3.addWidget(self.preLabel)
        self.preNumLabel = QtWidgets.QLabel(self.preRightWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.preNumLabel.sizePolicy().hasHeightForWidth())
        self.preNumLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(48)
        self.preNumLabel.setFont(font)
        self.preNumLabel.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.preNumLabel.setFrameShadow(QtWidgets.QFrame.Plain)
        self.preNumLabel.setText("")
        self.preNumLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.preNumLabel.setObjectName("preNumLabel")
        self.verticalLayout_3.addWidget(self.preNumLabel)
        self.verticalLayout_6.addLayout(self.verticalLayout_3)
        self.gridLayout_3.addWidget(self.preRightWidget, 0, 2, 1, 1)
        self.gridLayout_3.setColumnStretch(0, 1)
        self.gridLayout_3.setColumnStretch(1, 6)
        self.gridLayout_3.setColumnStretch(2, 1)
        self.gridLayout_5.addLayout(self.gridLayout_3, 0, 0, 1, 1)
        self.tabWidget.addTab(self.preWidget, "")
        self.mainGridLayout.addWidget(self.tabWidget, 1, 0, 1, 2)
        self.mainGridLayout.setColumnStretch(0, 1)
        self.mainGridLayout.setColumnStretch(1, 1)
        self.mainGridLayout.setRowStretch(0, 1)
        self.mainGridLayout.setRowStretch(1, 30)
        self.horizontalLayout_2.addLayout(self.mainGridLayout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Scilence Speech System"))
        self.titlelabel.setToolTip(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.titlelabel.setText(_translate("MainWindow", "Silence Speech System"))
        self.label_1.setText(_translate("MainWindow", "请说："))
        self.label_2.setText(_translate("MainWindow", "你说了："))
        self.startTrain.setText(_translate("MainWindow", "开始训练"))
        self.stopTrain.setText(_translate("MainWindow", "停止训练"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.trainWidget), _translate("MainWindow", "训练系统"))
        self.selectLabel.setText(_translate("MainWindow", "请选择："))
        __sortingEnabled = self.listPreWidget.isSortingEnabled()
        self.listPreWidget.setSortingEnabled(False)
        item = self.listPreWidget.item(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.listPreWidget.item(1)
        item.setText(_translate("MainWindow", "5"))
        item = self.listPreWidget.item(2)
        item.setText(_translate("MainWindow", "8"))
        self.listPreWidget.setSortingEnabled(__sortingEnabled)
        self.startPreButton.setText(_translate("MainWindow", "启动"))
        self.stopPreButton.setText(_translate("MainWindow", "停止"))
        self.preLabel.setText(_translate("MainWindow", "实时预测："))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.preWidget), _translate("MainWindow", "预测系统"))

